# Generated by Django 5.1.3 on 2024-11-19 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_customer_delivery_driver_restaurant_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('menu_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=100)),
                ('item_description', models.CharField(max_length=500)),
                ('item_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('restaurant_name2', models.CharField(max_length=100)),
            ],
        ),
    ]
