# Generated by Django 5.1.3 on 2024-11-19 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0003_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='menu_images/'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='delivery_driver',
            name='driver_phone_number',
            field=models.IntegerField(),
        ),
    ]
