# Generated by Django 5.1.3 on 2024-11-19 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0004_menu_image_alter_customer_phone_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='image',
        ),
    ]
