# Generated by Django 5.1.3 on 2024-11-20 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0008_menu_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
