# Generated by Django 5.1.3 on 2024-11-22 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0010_alter_customer_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='total_amount',
        ),
    ]
