# Generated by Django 5.1.3 on 2024-11-23 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0012_alter_orders_order_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='delivery_address',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='estimated_delivery_time',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='order_date',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='order_item',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='status',
        ),
    ]
