# Generated by Django 5.1.3 on 2024-11-23 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0013_remove_orders_delivery_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='delivery_address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='order_description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='order_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='order_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='orders_image',
            field=models.ImageField(blank=True, null=True, upload_to='menu_images/'),
        ),
    ]
