# Generated by Django 5.1.3 on 2024-11-24 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0015_delivery_driver_driver_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='order_customer',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
