# Generated by Django 5.1.3 on 2024-11-30 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0016_orders_order_customer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Restaurant',
        ),
    ]
